<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Caroline Atuhaire">

<title>projectworkrevised</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="projectworkrevised_files/libs/clipboard/clipboard.min.js"></script>
<script src="projectworkrevised_files/libs/quarto-html/quarto.js"></script>
<script src="projectworkrevised_files/libs/quarto-html/popper.min.js"></script>
<script src="projectworkrevised_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="projectworkrevised_files/libs/quarto-html/anchor.min.js"></script>
<link href="projectworkrevised_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="projectworkrevised_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="projectworkrevised_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="projectworkrevised_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="projectworkrevised_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">projectworkrevised</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Caroline Atuhaire </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="load-libraries" class="level3">
<h3 class="anchored" data-anchor-id="load-libraries">Load Libraries</h3>
<p>We begin by loading the necessary R packages for data manipulation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidycensus)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tigris)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Silence messages from tidycensus</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">tidycensus.quiet =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-data-sets" class="level3">
<h3 class="anchored" data-anchor-id="load-data-sets">Load data sets</h3>
<p>We define the file path where the SNAP administrative data is stored locally. Using list.files(), we then identify and list all Excel files (.xls) within the directory for later processing.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define your local file path </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>data_path <span class="ot">&lt;-</span> <span class="st">"C:/Users/Caroline/Desktop/MIDP SEMESTER IV/Introduction to Data Science R/stretchassignment08data/snap-zip-fns388a-4"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># List all Excel files in that folder</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>file_list <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="at">path =</span> data_path, <span class="at">pattern =</span> <span class="st">"</span><span class="sc">\\</span><span class="st">.xls$"</span>, <span class="at">full.names =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="read-the-snap-files-in" class="level3">
<h3 class="anchored" data-anchor-id="read-the-snap-files-in">Read the SNAP files in</h3>
<p>We define a custom function read_snap_file() to import and clean each Excel file in the SNAP administrative dataset. The function performs the following steps:</p>
<p>Data Import and Cleaning: It reads the file using read_excel(), skipping the first three rows which contain metadata, and cleans the column names with janitor::clean_names(). It also removes any empty or placeholder columns.</p>
<p>Metadata Extraction: The function extracts the month (JAN or JUL) and year from the file name and stores them as new variables. If the year is missing or the key column substate_region is not present, the function returns NULL to skip invalid files.</p>
<p>Variable Construction: It constructs standardized columns including date, region_code, state, county, and office_type by parsing text from the substate_region column.</p>
<p>Variable Selection: Only relevant columns related to participation and issuance (e.g., persons and households by assistance type, total issuance) are retained for further analysis.</p>
<p>This function enables consistent extraction and cleaning of variables across multiple Excel files with</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>read_snap_file <span class="ot">&lt;-</span> <span class="cf">function</span>(file_path) {</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  snap_df <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(file_path, <span class="at">skip =</span> <span class="dv">3</span>) <span class="sc">%&gt;%</span> <span class="fu">clean_names</span>()</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  snap_df <span class="ot">&lt;-</span> snap_df <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="fu">matches</span>(<span class="st">"^</span><span class="sc">\\</span><span class="st">.</span><span class="sc">\\</span><span class="st">.</span><span class="sc">\\</span><span class="st">.|^x</span><span class="sc">\\</span><span class="st">d+$"</span>))  <span class="co"># drop empty columns</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  file_name <span class="ot">&lt;-</span> <span class="fu">basename</span>(file_path)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  month <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(file_name, <span class="st">"JAN|JUL"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  year <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(file_name, <span class="st">"(19|20)</span><span class="sc">\\</span><span class="st">d{2}"</span>) <span class="sc">%&gt;%</span> <span class="fu">as.numeric</span>()</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.na</span>(year) <span class="sc">|</span> <span class="sc">!</span><span class="st">"substate_region"</span> <span class="sc">%in%</span> <span class="fu">names</span>(snap_df)) <span class="fu">return</span>(<span class="cn">NULL</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  snap_df <span class="ot">&lt;-</span> snap_df <span class="sc">%&gt;%</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">month =</span> month,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">year =</span> year,</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">date =</span> <span class="fu">ym</span>(<span class="fu">paste</span>(year, month, <span class="st">"01"</span>)),</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">region_code =</span> <span class="fu">str_extract</span>(substate_region, <span class="st">"^</span><span class="sc">\\</span><span class="st">d+"</span>),</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">state =</span> <span class="fu">str_extract</span>(substate_region, <span class="st">"</span><span class="sc">\\</span><span class="st">b[A-Z]{2}</span><span class="sc">\\</span><span class="st">b"</span>),</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>      <span class="at">county =</span> <span class="fu">str_extract</span>(substate_region, <span class="st">"(?&lt;=EBT )[A-Z</span><span class="sc">\\</span><span class="st">s]+?(?= CO| FSO| FS OFFICE| FS OFF</span><span class="sc">\\</span><span class="st">.|$)"</span>),</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">county =</span> <span class="fu">str_remove</span>(county, <span class="st">"</span><span class="sc">\\</span><span class="st">s+CO</span><span class="sc">\\</span><span class="st">b"</span>) <span class="sc">%&gt;%</span> <span class="fu">str_trim</span>(),</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>      <span class="at">office_type =</span> <span class="fu">str_extract</span>(substate_region, <span class="st">"CO FS OFF|FSO|FS OFFICE|FS OFF</span><span class="sc">\\</span><span class="st">."</span>) <span class="sc">%&gt;%</span> <span class="fu">str_trim</span>()</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>      date, year, month, state, region_code, county, office_type,</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>      snap_all_persons_public_assistance_participation,</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>      snap_all_persons_non_public_assistance_participation,</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>      calc_snap_total_pa_and_non_pa_people,</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>      snap_all_households_public_assistance_participation,</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>      snap_all_households_non_public_assistance_participation,</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>      calc_snap_total_pa_and_non_pa_households,</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>      snap_all_total_actual_pa_non_pa_issuance</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(snap_df)</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We apply the read_snap_file() function to each Excel file using purrr::map_dfr() to efficiently read and combine them into a single tidy data frame, snap_all. To ensure robustness, we wrap the function call in possibly(), which safely skips files that fail to load or parse correctly by returning NULL. We then filter the combined dataset to include only records from 2015 onward. Finally, we use glimpse() to preview the structure of the resulting dataset and verify successful loading and cleaning of the variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define your file path from Step 1</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>data_path <span class="ot">&lt;-</span> <span class="st">"C:/Users/Caroline/Desktop/MIDP SEMESTER IV/Introduction to Data Science R/stretchassignment08data/snap-zip-fns388a-4"</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># List all Excel files in the folder</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>file_list <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="at">path =</span> data_path, <span class="at">pattern =</span> <span class="st">"</span><span class="sc">\\</span><span class="st">.xls$"</span>, <span class="at">full.names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Read and combine all SNAP files</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>snap_all <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(file_list, <span class="fu">possibly</span>(read_snap_file, <span class="at">otherwise =</span> <span class="cn">NULL</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">&gt;=</span> <span class="dv">2015</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2845 / R2845C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2850 / R2850C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2863 / R2863C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2880 / R2880C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2800 / R2800C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2768 / R2768C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2788 / R2788C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2845 / R2845C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2826 / R2826C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2927 / R2927C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B3476 / R3476C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B3174 / R3174C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2893 / R2893C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2873 / R2873C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2763 / R2763C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2721 / R2721C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2783 / R2783C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2773 / R2773C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2826 / R2826C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2712 / R2712C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2710 / R2710C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2704 / R2704C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2703 / R2703C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2704 / R2704C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2683 / R2683C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2738 / R2738C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2734 / R2734C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2733 / R2733C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2637 / R2637C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
New names:
New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2842 / R2842C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2850 / R2850C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2876 / R2876C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2786 / R2786C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2787 / R2787C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2766 / R2766C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2907 / R2907C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2850 / R2850C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2813 / R2813C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B3442 / R3442C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B3358 / R3358C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B3044 / R3044C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2794 / R2794C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2747 / R2747C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2762 / R2762C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2723 / R2723C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2776 / R2776C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2777 / R2777C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2712 / R2712C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2712 / R2712C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2704 / R2704C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2704 / R2704C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2703 / R2703C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2678 / R2678C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2678 / R2678C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2683 / R2683C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2733 / R2733C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2734 / R2734C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting numeric in B2731 / R2731C2: got 'a  Automated system generated estimate
b  Budget analyst generated estimate'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
New names:
New names:
• `` -&gt; `...3`
• `` -&gt; `...5`
• `` -&gt; `...7`
• `` -&gt; `...9`
• `` -&gt; `...11`
• `` -&gt; `...13`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview</span></span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(snap_all)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 29,567
Columns: 14
$ date                                                    &lt;date&gt; 2015-01-01, 2…
$ year                                                    &lt;dbl&gt; 2015, 2015, 20…
$ month                                                   &lt;chr&gt; NA, NA, NA, NA…
$ state                                                   &lt;chr&gt; "AL", "AL", "A…
$ region_code                                             &lt;chr&gt; "0100101", "01…
$ county                                                  &lt;chr&gt; "AUTAUGA", "BA…
$ office_type                                             &lt;chr&gt; "CO FS OFF", "…
$ snap_all_persons_public_assistance_participation        &lt;dbl&gt; 1160, 2115, 96…
$ snap_all_persons_non_public_assistance_participation    &lt;dbl&gt; 7094, 22733, 5…
$ calc_snap_total_pa_and_non_pa_people                    &lt;dbl&gt; 8254, 24848, 6…
$ snap_all_households_public_assistance_participation     &lt;dbl&gt; 502, 1045, 466…
$ snap_all_households_non_public_assistance_participation &lt;dbl&gt; 3187, 9523, 27…
$ calc_snap_total_pa_and_non_pa_households                &lt;dbl&gt; 3689, 10568, 3…
$ snap_all_total_actual_pa_non_pa_issuance                &lt;dbl&gt; 1018843, 30904…</code></pre>
</div>
</div>
<p>We load our Census API key and using the tidycensus package to download county-level data from the 2021 ACS 5-Year Estimates. Specifically, we retrieve the number of total households and the number of households receiving SNAP benefits using variables B19058_001 and B19058_002. The data is then cleaned and reshaped into a wide format to calculate the SNAP participation rate (snap_rate) as the proportion of households receiving SNAP benefits relative to total households. We also extract the state FIPS code from the GEOID for summarization purposes. Finally, we compute and display the total number of unique states and counties represented in the dataset, which confirms comprehensive geographic coverage.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Load API key</span></span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a><span class="fu">census_api_key</span>(<span class="st">"dd8db12242afbd7567dab7970c3909117dab6ca0"</span>, <span class="at">install =</span> <span class="cn">TRUE</span>, <span class="at">overwrite =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Your original .Renviron will be backed up and stored in your R HOME directory if needed.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Your API key has been stored in your .Renviron and can be accessed by Sys.getenv("CENSUS_API_KEY"). 
To use now, restart R or run `readRenviron("~/.Renviron")`</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "dd8db12242afbd7567dab7970c3909117dab6ca0"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Download ACS county-level SNAP household data</span></span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a>snap_county <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"county"</span>,</span>
<span id="cb127-4"><a href="#cb127-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="fu">c</span>(</span>
<span id="cb127-5"><a href="#cb127-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_households =</span> <span class="st">"B19058_001"</span>,</span>
<span id="cb127-6"><a href="#cb127-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">snap_households  =</span> <span class="st">"B19058_002"</span></span>
<span id="cb127-7"><a href="#cb127-7" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb127-8"><a href="#cb127-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="dv">2019</span>,</span>
<span id="cb127-9"><a href="#cb127-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey =</span> <span class="st">"acs5"</span>,</span>
<span id="cb127-10"><a href="#cb127-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">geometry =</span> <span class="cn">FALSE</span>,</span>
<span id="cb127-11"><a href="#cb127-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">cache_table =</span> <span class="cn">TRUE</span></span>
<span id="cb127-12"><a href="#cb127-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Getting data from the 2015-2019 5-year ACS</code></pre>
</div>
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Clean and prepare ACS data</span></span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a>snap_county_clean <span class="ot">&lt;-</span> snap_county <span class="sc">%&gt;%</span></span>
<span id="cb129-3"><a href="#cb129-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(GEOID, NAME, variable, estimate) <span class="sc">%&gt;%</span></span>
<span id="cb129-4"><a href="#cb129-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> variable, <span class="at">values_from =</span> estimate) <span class="sc">%&gt;%</span></span>
<span id="cb129-5"><a href="#cb129-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb129-6"><a href="#cb129-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">county =</span> <span class="fu">str_remove</span>(NAME, <span class="st">" County,.*"</span>),</span>
<span id="cb129-7"><a href="#cb129-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">state =</span> <span class="fu">str_extract</span>(NAME, <span class="st">",</span><span class="sc">\\</span><span class="st">s*.*$"</span>) <span class="sc">%&gt;%</span> <span class="fu">str_remove</span>(<span class="st">",</span><span class="sc">\\</span><span class="st">s*"</span>),</span>
<span id="cb129-8"><a href="#cb129-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">state =</span> <span class="fu">str_trim</span>(state),</span>
<span id="cb129-9"><a href="#cb129-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">county =</span> <span class="fu">str_trim</span>(county)</span>
<span id="cb129-10"><a href="#cb129-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb129-11"><a href="#cb129-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb129-12"><a href="#cb129-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_households =</span> total_households,</span>
<span id="cb129-13"><a href="#cb129-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">fips =</span> GEOID</span>
<span id="cb129-14"><a href="#cb129-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb129-15"><a href="#cb129-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(fips, state, county, total_households)</span>
<span id="cb129-16"><a href="#cb129-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-17"><a href="#cb129-17" aria-hidden="true" tabindex="-1"></a>snap_county <span class="ot">&lt;-</span> snap_county <span class="sc">%&gt;%</span></span>
<span id="cb129-18"><a href="#cb129-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(GEOID, NAME, variable, estimate) <span class="sc">%&gt;%</span></span>
<span id="cb129-19"><a href="#cb129-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> variable, <span class="at">values_from =</span> estimate) <span class="sc">%&gt;%</span></span>
<span id="cb129-20"><a href="#cb129-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb129-21"><a href="#cb129-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">snap_rate =</span> snap_households <span class="sc">/</span> total_households,</span>
<span id="cb129-22"><a href="#cb129-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">state_fips =</span> <span class="fu">str_sub</span>(GEOID, <span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb129-23"><a href="#cb129-23" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb129-24"><a href="#cb129-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-25"><a href="#cb129-25" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Summarize number of counties and states</span></span>
<span id="cb129-26"><a href="#cb129-26" aria-hidden="true" tabindex="-1"></a>acs_summary <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb129-27"><a href="#cb129-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">level =</span> <span class="fu">c</span>(<span class="st">"State"</span>, <span class="st">"County"</span>),</span>
<span id="cb129-28"><a href="#cb129-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">count =</span> <span class="fu">c</span>(</span>
<span id="cb129-29"><a href="#cb129-29" aria-hidden="true" tabindex="-1"></a>    <span class="fu">n_distinct</span>(snap_county<span class="sc">$</span>state_fips),</span>
<span id="cb129-30"><a href="#cb129-30" aria-hidden="true" tabindex="-1"></a>    <span class="fu">n_distinct</span>(snap_county<span class="sc">$</span>GEOID)</span>
<span id="cb129-31"><a href="#cb129-31" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb129-32"><a href="#cb129-32" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb129-33"><a href="#cb129-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-34"><a href="#cb129-34" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. Print summary</span></span>
<span id="cb129-35"><a href="#cb129-35" aria-hidden="true" tabindex="-1"></a>acs_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  level  count
  &lt;chr&gt;  &lt;int&gt;
1 State     52
2 County  3220</code></pre>
</div>
</div>
<p>To ensure comparability across datasets, we first exclude U.S. territories from both the SNAP administrative data and the ACS demographic data using their FIPS codes and postal abbreviations. We then identify the number of unique states and counties present in each dataset by source. This summary allows us to assess the completeness of geographic coverage in both datasets and verify alignment prior to any merging or geospatial analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="co"># === Define U.S. Territories to Exclude ===</span></span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a>territory_fips <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"60"</span>, <span class="st">"66"</span>, <span class="st">"69"</span>, <span class="st">"72"</span>, <span class="st">"78"</span>)    <span class="co"># FIPS for AS, GU, MP, PR, VI</span></span>
<span id="cb131-3"><a href="#cb131-3" aria-hidden="true" tabindex="-1"></a>territory_abbr <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"AS"</span>, <span class="st">"GU"</span>, <span class="st">"MP"</span>, <span class="st">"PR"</span>, <span class="st">"VI"</span>)    <span class="co"># Postal codes</span></span>
<span id="cb131-4"><a href="#cb131-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-5"><a href="#cb131-5" aria-hidden="true" tabindex="-1"></a><span class="co"># === 1. Clean SNAP Data: Drop Territories and NAs ===</span></span>
<span id="cb131-6"><a href="#cb131-6" aria-hidden="true" tabindex="-1"></a>snap_all <span class="ot">&lt;-</span> snap_all <span class="sc">%&gt;%</span></span>
<span id="cb131-7"><a href="#cb131-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>state <span class="sc">%in%</span> territory_abbr, <span class="sc">!</span><span class="fu">is.na</span>(state), <span class="sc">!</span><span class="fu">is.na</span>(county))</span>
<span id="cb131-8"><a href="#cb131-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-9"><a href="#cb131-9" aria-hidden="true" tabindex="-1"></a><span class="co"># === 2. Clean ACS Data: Drop Territories Based on FIPS ===</span></span>
<span id="cb131-10"><a href="#cb131-10" aria-hidden="true" tabindex="-1"></a>snap_county <span class="ot">&lt;-</span> snap_county <span class="sc">%&gt;%</span></span>
<span id="cb131-11"><a href="#cb131-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">str_sub</span>(GEOID, <span class="dv">1</span>, <span class="dv">2</span>) <span class="sc">%in%</span> territory_fips)</span>
<span id="cb131-12"><a href="#cb131-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-13"><a href="#cb131-13" aria-hidden="true" tabindex="-1"></a><span class="co"># === 3. Unique States by Source ===</span></span>
<span id="cb131-14"><a href="#cb131-14" aria-hidden="true" tabindex="-1"></a>snap_states <span class="ot">&lt;-</span> snap_all <span class="sc">%&gt;%</span></span>
<span id="cb131-15"><a href="#cb131-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(state) <span class="sc">%&gt;%</span></span>
<span id="cb131-16"><a href="#cb131-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">level =</span> <span class="st">"State"</span>, <span class="at">source =</span> <span class="st">"SNAP"</span>)</span>
<span id="cb131-17"><a href="#cb131-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-18"><a href="#cb131-18" aria-hidden="true" tabindex="-1"></a>acs_states <span class="ot">&lt;-</span> snap_county <span class="sc">%&gt;%</span></span>
<span id="cb131-19"><a href="#cb131-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">state =</span> <span class="fu">str_sub</span>(GEOID, <span class="dv">1</span>, <span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb131-20"><a href="#cb131-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(state) <span class="sc">%&gt;%</span></span>
<span id="cb131-21"><a href="#cb131-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">level =</span> <span class="st">"State"</span>, <span class="at">source =</span> <span class="st">"ACS"</span>)</span>
<span id="cb131-22"><a href="#cb131-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-23"><a href="#cb131-23" aria-hidden="true" tabindex="-1"></a><span class="co"># === 4. Unique Counties by Source ===</span></span>
<span id="cb131-24"><a href="#cb131-24" aria-hidden="true" tabindex="-1"></a>snap_counties <span class="ot">&lt;-</span> snap_all <span class="sc">%&gt;%</span></span>
<span id="cb131-25"><a href="#cb131-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(state, county) <span class="sc">%&gt;%</span></span>
<span id="cb131-26"><a href="#cb131-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">level =</span> <span class="st">"County"</span>, <span class="at">source =</span> <span class="st">"SNAP"</span>)</span>
<span id="cb131-27"><a href="#cb131-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-28"><a href="#cb131-28" aria-hidden="true" tabindex="-1"></a>acs_counties <span class="ot">&lt;-</span> snap_county <span class="sc">%&gt;%</span></span>
<span id="cb131-29"><a href="#cb131-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">state =</span> <span class="fu">str_sub</span>(GEOID, <span class="dv">1</span>, <span class="dv">2</span>),</span>
<span id="cb131-30"><a href="#cb131-30" aria-hidden="true" tabindex="-1"></a>         <span class="at">county =</span> <span class="fu">str_sub</span>(GEOID, <span class="dv">3</span>, <span class="dv">5</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb131-31"><a href="#cb131-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(state, county) <span class="sc">%&gt;%</span></span>
<span id="cb131-32"><a href="#cb131-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">level =</span> <span class="st">"County"</span>, <span class="at">source =</span> <span class="st">"ACS"</span>)</span>
<span id="cb131-33"><a href="#cb131-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-34"><a href="#cb131-34" aria-hidden="true" tabindex="-1"></a><span class="co"># === 5. Combine and Summarize ===</span></span>
<span id="cb131-35"><a href="#cb131-35" aria-hidden="true" tabindex="-1"></a>coverage_summary <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(snap_states, acs_states, snap_counties, acs_counties) <span class="sc">%&gt;%</span></span>
<span id="cb131-36"><a href="#cb131-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(source, level) <span class="sc">%&gt;%</span></span>
<span id="cb131-37"><a href="#cb131-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb131-38"><a href="#cb131-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> level, <span class="at">values_from =</span> n)</span>
<span id="cb131-39"><a href="#cb131-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-40"><a href="#cb131-40" aria-hidden="true" tabindex="-1"></a><span class="co"># === 6. Display Summary Table ===</span></span>
<span id="cb131-41"><a href="#cb131-41" aria-hidden="true" tabindex="-1"></a>coverage_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  source County State
  &lt;chr&gt;   &lt;int&gt; &lt;int&gt;
1 ACS      3142    51
2 SNAP     2513    45</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>snap_states_list <span class="ot">&lt;-</span> snap_states <span class="sc">%&gt;%</span></span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(state) <span class="sc">%&gt;%</span></span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(state)</span>
<span id="cb133-4"><a href="#cb133-4" aria-hidden="true" tabindex="-1"></a>snap_states_list</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "AK" "AL" "AR" "AZ" "CA" "CO" "DE" "FL" "GA" "HI" "IA" "ID" "IL" "IN" "KS"
[16] "KY" "LA" "MA" "MD" "ME" "MI" "MN" "MS" "MT" "NC" "ND" "NE" "NJ" "NM" "NV"
[31] "NY" "OH" "OK" "PA" "RI" "SC" "SD" "TN" "TX" "VA" "VT" "WA" "WI" "WV" "WY"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tigris)</span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb135-3"><a href="#cb135-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb135-4"><a href="#cb135-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb135-5"><a href="#cb135-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb135-6"><a href="#cb135-6" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">tigris_use_cache =</span> <span class="cn">TRUE</span>)</span>
<span id="cb135-7"><a href="#cb135-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb135-8"><a href="#cb135-8" aria-hidden="true" tabindex="-1"></a><span class="co"># === 1. Load US states shapefile ===</span></span>
<span id="cb135-9"><a href="#cb135-9" aria-hidden="true" tabindex="-1"></a>us_states <span class="ot">&lt;-</span> <span class="fu">states</span>(<span class="at">cb =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb135-10"><a href="#cb135-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>STUSPS <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"AS"</span>, <span class="st">"GU"</span>, <span class="st">"MP"</span>, <span class="st">"PR"</span>, <span class="st">"VI"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb135-11"><a href="#cb135-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">state_abbr =</span> STUSPS, geometry)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Retrieving data for the year 2021</code></pre>
</div>
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="co"># === 2. Get SNAP state codes (already prepared as `snap_states`)</span></span>
<span id="cb137-2"><a href="#cb137-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Note: if your codes are FIPS (e.g. "01"), convert to abbrev</span></span>
<span id="cb137-3"><a href="#cb137-3" aria-hidden="true" tabindex="-1"></a>snap_present_states <span class="ot">&lt;-</span> snap_states<span class="sc">$</span>state</span>
<span id="cb137-4"><a href="#cb137-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-5"><a href="#cb137-5" aria-hidden="true" tabindex="-1"></a><span class="co"># === Load high-resolution U.S. states shapefile (includes DC more clearly) ===</span></span>
<span id="cb137-6"><a href="#cb137-6" aria-hidden="true" tabindex="-1"></a>us_states <span class="ot">&lt;-</span> tigris<span class="sc">::</span><span class="fu">states</span>(<span class="at">cb =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb137-7"><a href="#cb137-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>STUSPS <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"AS"</span>, <span class="st">"GU"</span>, <span class="st">"MP"</span>, <span class="st">"PR"</span>, <span class="st">"VI"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb137-8"><a href="#cb137-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">state_abbr =</span> STUSPS, geometry)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Retrieving data for the year 2021</code></pre>
</div>
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="co"># === 3. Create Present/Missing status</span></span>
<span id="cb139-2"><a href="#cb139-2" aria-hidden="true" tabindex="-1"></a>snap_state_map <span class="ot">&lt;-</span> us_states <span class="sc">%&gt;%</span></span>
<span id="cb139-3"><a href="#cb139-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb139-4"><a href="#cb139-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">status =</span> <span class="fu">ifelse</span>(state_abbr <span class="sc">%in%</span> snap_present_states, <span class="st">"Present"</span>, <span class="st">"Missing"</span>)</span>
<span id="cb139-5"><a href="#cb139-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb139-6"><a href="#cb139-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb139-7"><a href="#cb139-7" aria-hidden="true" tabindex="-1"></a><span class="co"># === 4. Plot the map ===</span></span>
<span id="cb139-8"><a href="#cb139-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(snap_state_map) <span class="sc">+</span></span>
<span id="cb139-9"><a href="#cb139-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> status), <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb139-10"><a href="#cb139-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(</span>
<span id="cb139-11"><a href="#cb139-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Present"</span> <span class="ot">=</span> <span class="st">"#1f78b4"</span>, <span class="st">"Missing"</span> <span class="ot">=</span> <span class="st">"red"</span>),</span>
<span id="cb139-12"><a href="#cb139-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">"SNAP Data"</span></span>
<span id="cb139-13"><a href="#cb139-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb139-14"><a href="#cb139-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb139-15"><a href="#cb139-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"SNAP State Coverage in the United States"</span>,</span>
<span id="cb139-16"><a href="#cb139-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"States missing from SNAP administrative data are shown in gray"</span>,</span>
<span id="cb139-17"><a href="#cb139-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source: SNAP administrative data and U.S. Census (ACS)"</span></span>
<span id="cb139-18"><a href="#cb139-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb139-19"><a href="#cb139-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb139-20"><a href="#cb139-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb139-21"><a href="#cb139-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">16</span>),</span>
<span id="cb139-22"><a href="#cb139-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb139-23"><a href="#cb139-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"bottom"</span></span>
<span id="cb139-24"><a href="#cb139-24" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb139-25"><a href="#cb139-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">crs =</span> <span class="dv">2163</span>)  <span class="co"># Better US projection</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in CPL_crs_from_input(x): GDAL Message 1: CRS EPSG:2163 is deprecated.
Its non-deprecated replacement EPSG:9311 will be used instead. To use the
original CRS, set the OSR_USE_NON_DEPRECATED configuration option to NO.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projectworkrevised_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>Although our earlier summary indicated that six states are missing from the SNAP administrative dataset, the map visualization displays only five in red. Upon closer inspection, we find that the missing state not shown on the map is the District of Columbia (DC).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="co"># All 50 states + DC (postal codes)</span></span>
<span id="cb141-2"><a href="#cb141-2" aria-hidden="true" tabindex="-1"></a>all_states <span class="ot">&lt;-</span> state.abb</span>
<span id="cb141-3"><a href="#cb141-3" aria-hidden="true" tabindex="-1"></a>all_states <span class="ot">&lt;-</span> <span class="fu">c</span>(all_states, <span class="st">"DC"</span>)  <span class="co"># Add DC if your data includes it</span></span>
<span id="cb141-4"><a href="#cb141-4" aria-hidden="true" tabindex="-1"></a>snap_states_present <span class="ot">&lt;-</span> <span class="fu">unique</span>(snap_all<span class="sc">$</span>state)</span>
<span id="cb141-5"><a href="#cb141-5" aria-hidden="true" tabindex="-1"></a>missing_states_in_snap <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(all_states, snap_states_present)</span>
<span id="cb141-6"><a href="#cb141-6" aria-hidden="true" tabindex="-1"></a>missing_states_in_snap</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "CT" "MO" "NH" "OR" "UT" "DC"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tigris)</span>
<span id="cb143-2"><a href="#cb143-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb143-3"><a href="#cb143-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb143-4"><a href="#cb143-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb143-5"><a href="#cb143-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb143-6"><a href="#cb143-6" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">tigris_use_cache =</span> <span class="cn">TRUE</span>)</span>
<span id="cb143-7"><a href="#cb143-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb143-8"><a href="#cb143-8" aria-hidden="true" tabindex="-1"></a><span class="co"># === 1. Load U.S. county shapefile ===</span></span>
<span id="cb143-9"><a href="#cb143-9" aria-hidden="true" tabindex="-1"></a>us_counties <span class="ot">&lt;-</span> <span class="fu">counties</span>(<span class="at">cb =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb143-10"><a href="#cb143-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>STATEFP <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"60"</span>, <span class="st">"66"</span>, <span class="st">"69"</span>, <span class="st">"72"</span>, <span class="st">"78"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb143-11"><a href="#cb143-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">GEOID =</span> <span class="fu">paste0</span>(STATEFP, COUNTYFP))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Retrieving data for the year 2022</code></pre>
</div>
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="co"># === 2. Prepare GEOID from SNAP data ===</span></span>
<span id="cb145-2"><a href="#cb145-2" aria-hidden="true" tabindex="-1"></a>snap_geoids <span class="ot">&lt;-</span> snap_all <span class="sc">%&gt;%</span></span>
<span id="cb145-3"><a href="#cb145-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(state), <span class="sc">!</span><span class="fu">is.na</span>(region_code)) <span class="sc">%&gt;%</span></span>
<span id="cb145-4"><a href="#cb145-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb145-5"><a href="#cb145-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">GEOID =</span> <span class="fu">str_sub</span>(region_code, <span class="dv">1</span>, <span class="dv">5</span>)  <span class="co"># Extract standard 5-digit FIPS code</span></span>
<span id="cb145-6"><a href="#cb145-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb145-7"><a href="#cb145-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(GEOID)</span>
<span id="cb145-8"><a href="#cb145-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb145-9"><a href="#cb145-9" aria-hidden="true" tabindex="-1"></a><span class="co"># === 3. Tag counties as present or missing ===</span></span>
<span id="cb145-10"><a href="#cb145-10" aria-hidden="true" tabindex="-1"></a>county_map <span class="ot">&lt;-</span> us_counties <span class="sc">%&gt;%</span></span>
<span id="cb145-11"><a href="#cb145-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb145-12"><a href="#cb145-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">status =</span> <span class="fu">ifelse</span>(GEOID <span class="sc">%in%</span> snap_geoids<span class="sc">$</span>GEOID, <span class="st">"Present"</span>, <span class="st">"Missing"</span>)</span>
<span id="cb145-13"><a href="#cb145-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb145-14"><a href="#cb145-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb145-15"><a href="#cb145-15" aria-hidden="true" tabindex="-1"></a><span class="co"># === 4. Plot the map ===</span></span>
<span id="cb145-16"><a href="#cb145-16" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(county_map) <span class="sc">+</span></span>
<span id="cb145-17"><a href="#cb145-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> status), <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb145-18"><a href="#cb145-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(</span>
<span id="cb145-19"><a href="#cb145-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Present"</span> <span class="ot">=</span> <span class="st">"#1f78b4"</span>, <span class="st">"Missing"</span> <span class="ot">=</span> <span class="st">"gray80"</span>),</span>
<span id="cb145-20"><a href="#cb145-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">"SNAP Data"</span></span>
<span id="cb145-21"><a href="#cb145-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb145-22"><a href="#cb145-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb145-23"><a href="#cb145-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"SNAP County Coverage in the United States"</span>,</span>
<span id="cb145-24"><a href="#cb145-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Counties missing from SNAP administrative data are shown in gray"</span>,</span>
<span id="cb145-25"><a href="#cb145-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source: SNAP administrative data"</span></span>
<span id="cb145-26"><a href="#cb145-26" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb145-27"><a href="#cb145-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">crs =</span> <span class="dv">2163</span>) <span class="sc">+</span></span>
<span id="cb145-28"><a href="#cb145-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb145-29"><a href="#cb145-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb145-30"><a href="#cb145-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb145-31"><a href="#cb145-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">16</span>),</span>
<span id="cb145-32"><a href="#cb145-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb145-33"><a href="#cb145-33" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projectworkrevised_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb146"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(snap_all)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 27,266
Columns: 14
$ date                                                    &lt;date&gt; 2015-01-01, 2…
$ year                                                    &lt;dbl&gt; 2015, 2015, 20…
$ month                                                   &lt;chr&gt; NA, NA, NA, NA…
$ state                                                   &lt;chr&gt; "AL", "AL", "A…
$ region_code                                             &lt;chr&gt; "0100101", "01…
$ county                                                  &lt;chr&gt; "AUTAUGA", "BA…
$ office_type                                             &lt;chr&gt; "CO FS OFF", "…
$ snap_all_persons_public_assistance_participation        &lt;dbl&gt; 1160, 2115, 96…
$ snap_all_persons_non_public_assistance_participation    &lt;dbl&gt; 7094, 22733, 5…
$ calc_snap_total_pa_and_non_pa_people                    &lt;dbl&gt; 8254, 24848, 6…
$ snap_all_households_public_assistance_participation     &lt;dbl&gt; 502, 1045, 466…
$ snap_all_households_non_public_assistance_participation &lt;dbl&gt; 3187, 9523, 27…
$ calc_snap_total_pa_and_non_pa_households                &lt;dbl&gt; 3689, 10568, 3…
$ snap_all_total_actual_pa_non_pa_issuance                &lt;dbl&gt; 1018843, 30904…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb148"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb148-1"><a href="#cb148-1" aria-hidden="true" tabindex="-1"></a>snap_all <span class="sc">%&gt;%</span></span>
<span id="cb148-2"><a href="#cb148-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(state, region_code, county) <span class="sc">%&gt;%</span></span>
<span id="cb148-3"><a href="#cb148-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   state region_code county  
   &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;   
 1 AL    0100101     AUTAUGA 
 2 AL    0100301     BALDWIN 
 3 AL    0100501     BARBOUR 
 4 AL    0100701     BIBB    
 5 AL    0100901     BLOUNT  
 6 AL    0101101     BULLOCK 
 7 AL    0101301     BUTLER  
 8 AL    0101501     CALHOUN 
 9 AL    0101701     CHAMBERS
10 AL    0101901     CHEROKEE</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb150"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb150-1"><a href="#cb150-1" aria-hidden="true" tabindex="-1"></a>snap_all <span class="sc">%&gt;%</span></span>
<span id="cb150-2"><a href="#cb150-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">five_digit =</span> <span class="fu">str_sub</span>(region_code, <span class="dv">1</span>, <span class="dv">5</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb150-3"><a href="#cb150-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(five_digit) <span class="sc">%&gt;%</span></span>
<span id="cb150-4"><a href="#cb150-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(five_digit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,508 × 2
   five_digit     n
   &lt;chr&gt;      &lt;int&gt;
 1 01001         11
 2 01003         11
 3 01005         11
 4 01007         11
 5 01009         11
 6 01011         11
 7 01013         11
 8 01015         11
 9 01017         11
10 01019         11
# ℹ 2,498 more rows</code></pre>
</div>
</div>
<p>This means that out of the 2,513 counties in SNAP FSN data, there are 2508 with the 5 digit FIPS code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb152"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb152-1"><a href="#cb152-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tigris)</span>
<span id="cb152-2"><a href="#cb152-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb152-3"><a href="#cb152-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb152-4"><a href="#cb152-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb152-5"><a href="#cb152-5" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">tigris_use_cache =</span> <span class="cn">TRUE</span>)</span>
<span id="cb152-6"><a href="#cb152-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb152-7"><a href="#cb152-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Get full county info (excluding territories)</span></span>
<span id="cb152-8"><a href="#cb152-8" aria-hidden="true" tabindex="-1"></a>us_counties <span class="ot">&lt;-</span> <span class="fu">counties</span>(<span class="at">cb =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb152-9"><a href="#cb152-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>STATEFP <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"60"</span>, <span class="st">"66"</span>, <span class="st">"69"</span>, <span class="st">"72"</span>, <span class="st">"78"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb152-10"><a href="#cb152-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">GEOID =</span> <span class="fu">paste0</span>(STATEFP, COUNTYFP))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Retrieving data for the year 2022</code></pre>
</div>
<div class="sourceCode cell-code" id="cb154"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb154-1"><a href="#cb154-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure missing_counties is defined and character</span></span>
<span id="cb154-2"><a href="#cb154-2" aria-hidden="true" tabindex="-1"></a>missing_counties <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(us_counties<span class="sc">$</span>GEOID, snap_all<span class="sc">$</span>region_code <span class="sc">%&gt;%</span> <span class="fu">str_sub</span>(<span class="dv">1</span>, <span class="dv">5</span>))</span>
<span id="cb154-3"><a href="#cb154-3" aria-hidden="true" tabindex="-1"></a>missing_counties <span class="ot">&lt;-</span> <span class="fu">as.character</span>(missing_counties)</span>
<span id="cb154-4"><a href="#cb154-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb154-5"><a href="#cb154-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Join with missing GEOIDs</span></span>
<span id="cb154-6"><a href="#cb154-6" aria-hidden="true" tabindex="-1"></a>missing_county_info <span class="ot">&lt;-</span> us_counties <span class="sc">%&gt;%</span></span>
<span id="cb154-7"><a href="#cb154-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(GEOID <span class="sc">%in%</span> missing_counties) <span class="sc">%&gt;%</span></span>
<span id="cb154-8"><a href="#cb154-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">state_name =</span> STATE_NAME, <span class="at">county_name =</span> NAME, GEOID)</span>
<span id="cb154-9"><a href="#cb154-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb154-10"><a href="#cb154-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Print (first 20)</span></span>
<span id="cb154-11"><a href="#cb154-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(missing_county_info, <span class="at">n =</span> <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 664 features and 3 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -179.1467 ymin: 21.12948 xmax: 179.7785 ymax: 71.38782
Geodetic CRS:  NAD83
First 20 features:
      state_name       county_name GEOID                       geometry
1        Arizona            La Paz 04012 MULTIPOLYGON (((-114.7312 3...
2       Delaware            Sussex 10005 MULTIPOLYGON (((-75.7226 38...
3        Florida        Miami-Dade 12086 MULTIPOLYGON (((-80.17628 2...
4          Idaho            Canyon 16027 MULTIPOLYGON (((-117.0319 4...
5       New York          Onondaga 36067 MULTIPOLYGON (((-76.49931 4...
6       New York            Orange 36071 MULTIPOLYGON (((-74.76247 4...
7       New York          Chenango 36017 MULTIPOLYGON (((-75.88983 4...
8          Maine              Knox 23013 MULTIPOLYGON (((-68.55926 4...
9          Maine           Lincoln 23015 MULTIPOLYGON (((-69.32357 4...
10        Alaska Matanuska-Susitna 02170 MULTIPOLYGON (((-153.0019 6...
11        Alaska     Yukon-Koyukuk 02290 MULTIPOLYGON (((-161.0482 6...
12 Massachusetts        Barnstable 25001 MULTIPOLYGON (((-70.68698 4...
13 Massachusetts           Hampden 25013 MULTIPOLYGON (((-73.07484 4...
14      Missouri    Cape Girardeau 29031 MULTIPOLYGON (((-89.8668 37...
15      Missouri             Scott 29201 MULTIPOLYGON (((-89.78682 3...
16      Missouri          Harrison 29081 MULTIPOLYGON (((-94.23224 4...
17       Montana          Gallatin 30031 MULTIPOLYGON (((-111.8053 4...
18       Montana          Phillips 30071 MULTIPOLYGON (((-108.8911 4...
19       Montana         Roosevelt 30085 MULTIPOLYGON (((-105.844 48...
20       Montana           Sanders 30089 MULTIPOLYGON (((-116.0491 4...</code></pre>
</div>
</div>
<p>Out of 3,143 U.S. counties in the ACS data, 664 were missing from the SNAP administrative data. However, 655 of these counties still report SNAP participation rates in the ACS, indicating that most gaps in administrative coverage are supplemented by survey data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb156"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb156-1"><a href="#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tigris)</span>
<span id="cb156-2"><a href="#cb156-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb156-3"><a href="#cb156-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb156-4"><a href="#cb156-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb156-5"><a href="#cb156-5" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">tigris_use_cache =</span> <span class="cn">TRUE</span>)</span>
<span id="cb156-6"><a href="#cb156-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb156-7"><a href="#cb156-7" aria-hidden="true" tabindex="-1"></a><span class="co"># === Step 1: Get all U.S. counties (excluding territories) ===</span></span>
<span id="cb156-8"><a href="#cb156-8" aria-hidden="true" tabindex="-1"></a>us_counties <span class="ot">&lt;-</span> <span class="fu">counties</span>(<span class="at">cb =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb156-9"><a href="#cb156-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>STATEFP <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"60"</span>, <span class="st">"66"</span>, <span class="st">"69"</span>, <span class="st">"72"</span>, <span class="st">"78"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb156-10"><a href="#cb156-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">GEOID =</span> <span class="fu">paste0</span>(STATEFP, COUNTYFP))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Retrieving data for the year 2022</code></pre>
</div>
<div class="sourceCode cell-code" id="cb158"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb158-1"><a href="#cb158-1" aria-hidden="true" tabindex="-1"></a><span class="co"># === Step 2: Extract valid county FIPS codes from SNAP data ===</span></span>
<span id="cb158-2"><a href="#cb158-2" aria-hidden="true" tabindex="-1"></a>snap_fips <span class="ot">&lt;-</span> snap_all <span class="sc">%&gt;%</span></span>
<span id="cb158-3"><a href="#cb158-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">county_fips =</span> <span class="fu">str_sub</span>(region_code, <span class="dv">1</span>, <span class="dv">5</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb158-4"><a href="#cb158-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(county_fips) <span class="sc">%&gt;%</span></span>
<span id="cb158-5"><a href="#cb158-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(county_fips)</span>
<span id="cb158-6"><a href="#cb158-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb158-7"><a href="#cb158-7" aria-hidden="true" tabindex="-1"></a><span class="co"># === Step 3: Identify GEOIDs not covered in SNAP ===</span></span>
<span id="cb158-8"><a href="#cb158-8" aria-hidden="true" tabindex="-1"></a>missing_counties <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(us_counties<span class="sc">$</span>GEOID, snap_fips)</span>
<span id="cb158-9"><a href="#cb158-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb158-10"><a href="#cb158-10" aria-hidden="true" tabindex="-1"></a><span class="co"># === Step 4: Check if these missing counties appear in ACS ===</span></span>
<span id="cb158-11"><a href="#cb158-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure ACS GEOID is character</span></span>
<span id="cb158-12"><a href="#cb158-12" aria-hidden="true" tabindex="-1"></a>snap_county <span class="ot">&lt;-</span> snap_county <span class="sc">%&gt;%</span></span>
<span id="cb158-13"><a href="#cb158-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">GEOID =</span> <span class="fu">as.character</span>(GEOID))</span>
<span id="cb158-14"><a href="#cb158-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb158-15"><a href="#cb158-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for overlap</span></span>
<span id="cb158-16"><a href="#cb158-16" aria-hidden="true" tabindex="-1"></a>acs_overlap <span class="ot">&lt;-</span> snap_county <span class="sc">%&gt;%</span></span>
<span id="cb158-17"><a href="#cb158-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(GEOID <span class="sc">%in%</span> missing_counties)</span>
<span id="cb158-18"><a href="#cb158-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb158-19"><a href="#cb158-19" aria-hidden="true" tabindex="-1"></a><span class="co"># === Step 5: Summarize the result ===</span></span>
<span id="cb158-20"><a href="#cb158-20" aria-hidden="true" tabindex="-1"></a>n_overlap <span class="ot">&lt;-</span> <span class="fu">nrow</span>(acs_overlap)</span>
<span id="cb158-21"><a href="#cb158-21" aria-hidden="true" tabindex="-1"></a>n_total_missing <span class="ot">&lt;-</span> <span class="fu">length</span>(missing_counties)</span>
<span id="cb158-22"><a href="#cb158-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb158-23"><a href="#cb158-23" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Of the"</span>, n_total_missing, <span class="st">"counties missing in SNAP data,"</span>, n_overlap,</span>
<span id="cb158-24"><a href="#cb158-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"have SNAP participation data in ACS.</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Of the 664 counties missing in SNAP data, 653 have SNAP participation data in ACS.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb160"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb160-1"><a href="#cb160-1" aria-hidden="true" tabindex="-1"></a><span class="co"># === Step 6: Preview counties with highest SNAP rate (optional) ===</span></span>
<span id="cb160-2"><a href="#cb160-2" aria-hidden="true" tabindex="-1"></a>acs_overlap <span class="sc">%&gt;%</span></span>
<span id="cb160-3"><a href="#cb160-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(GEOID, NAME, snap_households, total_households, snap_rate) <span class="sc">%&gt;%</span></span>
<span id="cb160-4"><a href="#cb160-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(snap_rate)) <span class="sc">%&gt;%</span></span>
<span id="cb160-5"><a href="#cb160-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 5
   GEOID NAME                         snap_households total_households snap_rate
   &lt;chr&gt; &lt;chr&gt;                                  &lt;dbl&gt;            &lt;dbl&gt;     &lt;dbl&gt;
 1 02158 Kusilvak Census Area, Alaska            1105             1724     0.641
 2 46102 Oglala Lakota County, South…            1621             2729     0.594
 3 46017 Buffalo County, South Dakota             295              564     0.523
 4 02050 Bethel Census Area, Alaska              1949             4489     0.434
 5 02188 Northwest Arctic Borough, A…             661             1795     0.368
 6 36005 Bronx County, New York                184575           503829     0.366
 7 02290 Yukon-Koyukuk Census Area, …             643             1856     0.346
 8 02180 Nome Census Area, Alaska                 983             2844     0.346
 9 29155 Pemiscot County, Missouri               2202             6730     0.327
10 29133 Mississippi County, Missouri            1637             5026     0.326</code></pre>
</div>
<div class="sourceCode cell-code" id="cb162"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb162-1"><a href="#cb162-1" aria-hidden="true" tabindex="-1"></a>n_total_missing <span class="ot">&lt;-</span> <span class="fu">length</span>(missing_counties)</span>
<span id="cb162-2"><a href="#cb162-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb162-3"><a href="#cb162-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary sentence using paste()</span></span>
<span id="cb162-4"><a href="#cb162-4" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Of the"</span>, n_total_missing, <span class="st">"counties missing in SNAP data,"</span>, </span>
<span id="cb162-5"><a href="#cb162-5" aria-hidden="true" tabindex="-1"></a>      n_overlap, <span class="st">"have SNAP participation data in ACS."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Of the 664 counties missing in SNAP data, 653 have SNAP participation data in ACS."</code></pre>
</div>
</div>
<p>Among the 664 counties missing from the SNAP administrative dataset, 655 have corresponding SNAP participation data available in the ACS dataset. This means that only 9 counties—less than 1.5% of those missing—are not represented in either dataset. Below are the missing counties</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb164"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb164-1"><a href="#cb164-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Get the list of counties missing in both SNAP and ACS</span></span>
<span id="cb164-2"><a href="#cb164-2" aria-hidden="true" tabindex="-1"></a>missing_both <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(missing_counties, snap_county<span class="sc">$</span>GEOID)</span>
<span id="cb164-3"><a href="#cb164-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb164-4"><a href="#cb164-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Pull their full names from the US counties shapefile</span></span>
<span id="cb164-5"><a href="#cb164-5" aria-hidden="true" tabindex="-1"></a>missing_both_info <span class="ot">&lt;-</span> us_counties <span class="sc">%&gt;%</span></span>
<span id="cb164-6"><a href="#cb164-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(GEOID <span class="sc">%in%</span> missing_both) <span class="sc">%&gt;%</span></span>
<span id="cb164-7"><a href="#cb164-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">state_name =</span> STATE_NAME, <span class="at">county_name =</span> NAME, GEOID)</span>
<span id="cb164-8"><a href="#cb164-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb164-9"><a href="#cb164-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Print them</span></span>
<span id="cb164-10"><a href="#cb164-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(missing_both_info, <span class="at">n =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 11 features and 3 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -148.7459 ymin: 40.98014 xmax: -71.78699 ymax: 63.21778
Geodetic CRS:  NAD83
    state_name                    county_name GEOID
1       Alaska                   Copper River 02066
2  Connecticut                        Capitol 09110
3  Connecticut      South Central Connecticut 09170
4  Connecticut       Southeastern Connecticut 09180
5  Connecticut Lower Connecticut River Valley 09130
6  Connecticut            Western Connecticut 09190
7  Connecticut               Naugatuck Valley 09140
8  Connecticut             Greater Bridgeport 09120
9  Connecticut                Northwest Hills 09160
10 Connecticut       Northeastern Connecticut 09150
11      Alaska                        Chugach 02063
                         geometry
1  MULTIPOLYGON (((-147.7443 6...
2  MULTIPOLYGON (((-72.95364 4...
3  MULTIPOLYGON (((-72.76143 4...
4  MULTIPOLYGON (((-72.22593 4...
5  MULTIPOLYGON (((-72.75294 4...
6  MULTIPOLYGON (((-73.72777 4...
7  MULTIPOLYGON (((-73.32684 4...
8  MULTIPOLYGON (((-73.21717 4...
9  MULTIPOLYGON (((-73.51795 4...
10 MULTIPOLYGON (((-72.22328 4...
11 MULTIPOLYGON (((-144.3945 6...</code></pre>
</div>
</div>
<p>To compute SNAP participation rates from administrative records, we first aggregated household participation data from the SNAP dataset by county using five-digit FIPS codes. Because the SNAP data contains multiple time points per county, we calculated the average number of participating households across all months for each county. We then merged this summary with ACS county-level data on total households and computed the administrative participation rate as the ratio of average SNAP households to total households. This allowed for a consistent comparison between the two data sources.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb166"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb166-1"><a href="#cb166-1" aria-hidden="true" tabindex="-1"></a>snap_admin_summary <span class="ot">&lt;-</span> snap_all <span class="sc">%&gt;%</span></span>
<span id="cb166-2"><a href="#cb166-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">GEOID =</span> <span class="fu">str_sub</span>(region_code, <span class="dv">1</span>, <span class="dv">5</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb166-3"><a href="#cb166-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(GEOID) <span class="sc">%&gt;%</span></span>
<span id="cb166-4"><a href="#cb166-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">snap_households_admin =</span> <span class="fu">mean</span>(</span>
<span id="cb166-5"><a href="#cb166-5" aria-hidden="true" tabindex="-1"></a>    snap_all_households_public_assistance_participation <span class="sc">+</span></span>
<span id="cb166-6"><a href="#cb166-6" aria-hidden="true" tabindex="-1"></a>    snap_all_households_non_public_assistance_participation, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb166-7"><a href="#cb166-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb166-8"><a href="#cb166-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb166-9"><a href="#cb166-9" aria-hidden="true" tabindex="-1"></a>snap_rates_combined <span class="ot">&lt;-</span> snap_county <span class="sc">%&gt;%</span></span>
<span id="cb166-10"><a href="#cb166-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(GEOID, <span class="at">total_households_acs =</span> total_households) <span class="sc">%&gt;%</span></span>
<span id="cb166-11"><a href="#cb166-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(snap_admin_summary, <span class="at">by =</span> <span class="st">"GEOID"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb166-12"><a href="#cb166-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">snap_admin_rate =</span> snap_households_admin <span class="sc">/</span> total_households_acs)</span>
<span id="cb166-13"><a href="#cb166-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb166-14"><a href="#cb166-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb166-15"><a href="#cb166-15" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(snap_rates_combined)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,142
Columns: 4
$ GEOID                 &lt;chr&gt; "01001", "01003", "01005", "01007", "01009", "01…
$ total_households_acs  &lt;dbl&gt; 21397, 80930, 9345, 6891, 20847, 3521, 6506, 446…
$ snap_households_admin &lt;dbl&gt; 3499.3636, 9422.7273, 2946.1818, 1645.2727, 3000…
$ snap_admin_rate       &lt;dbl&gt; 0.1635446, 0.1164306, 0.3152683, 0.2387567, 0.14…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb168"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb168-1"><a href="#cb168-1" aria-hidden="true" tabindex="-1"></a>snap_rates_combined <span class="ot">&lt;-</span> snap_rates_combined <span class="sc">%&gt;%</span></span>
<span id="cb168-2"><a href="#cb168-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fips =</span> <span class="fu">str_pad</span>(<span class="fu">as.character</span>(GEOID), <span class="dv">5</span>, <span class="at">pad =</span> <span class="st">"0"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb169"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb169-1"><a href="#cb169-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Load county shapefile (geometries)</span></span>
<span id="cb169-2"><a href="#cb169-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tigris)</span>
<span id="cb169-3"><a href="#cb169-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb169-4"><a href="#cb169-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb169-5"><a href="#cb169-5" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">tigris_use_cache =</span> <span class="cn">TRUE</span>)</span>
<span id="cb169-6"><a href="#cb169-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb169-7"><a href="#cb169-7" aria-hidden="true" tabindex="-1"></a>counties_sf <span class="ot">&lt;-</span> <span class="fu">counties</span>(<span class="at">cb =</span> <span class="cn">TRUE</span>, <span class="at">resolution =</span> <span class="st">"20m"</span>, <span class="at">class =</span> <span class="st">"sf"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb169-8"><a href="#cb169-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fips =</span> <span class="fu">str_pad</span>(<span class="fu">as.character</span>(GEOID), <span class="dv">5</span>, <span class="at">pad =</span> <span class="st">"0"</span>))  <span class="co"># Make sure FIPS is character</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Retrieving data for the year 2022</code></pre>
</div>
<div class="sourceCode cell-code" id="cb171"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb171-1"><a href="#cb171-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Join your SNAP data to the shapefile</span></span>
<span id="cb171-2"><a href="#cb171-2" aria-hidden="true" tabindex="-1"></a>snap_map_data <span class="ot">&lt;-</span> counties_sf <span class="sc">%&gt;%</span></span>
<span id="cb171-3"><a href="#cb171-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(snap_rates_combined, <span class="at">by =</span> <span class="st">"fips"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb171-4"><a href="#cb171-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(snap_admin_rate))  <span class="co"># Remove unmatched or missing rates</span></span>
<span id="cb171-5"><a href="#cb171-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb171-6"><a href="#cb171-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Plot the choropleth map</span></span>
<span id="cb171-7"><a href="#cb171-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb171-8"><a href="#cb171-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb171-9"><a href="#cb171-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> snap_map_data) <span class="sc">+</span></span>
<span id="cb171-10"><a href="#cb171-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> snap_admin_rate), <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb171-11"><a href="#cb171-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(</span>
<span id="cb171-12"><a href="#cb171-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">option =</span> <span class="st">"plasma"</span>,</span>
<span id="cb171-13"><a href="#cb171-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">"SNAP Participation Rate"</span>,</span>
<span id="cb171-14"><a href="#cb171-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> scales<span class="sc">::</span>percent</span>
<span id="cb171-15"><a href="#cb171-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb171-16"><a href="#cb171-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb171-17"><a href="#cb171-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"SNAP Participation Rate by County (Admin Data)"</span>,</span>
<span id="cb171-18"><a href="#cb171-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Admin Rate = Avg SNAP households (Admin) / Total households (ACS 2015–2019)"</span></span>
<span id="cb171-19"><a href="#cb171-19" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb171-20"><a href="#cb171-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projectworkrevised_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This code below summarizes the distribution of SNAP participation rates and identifies counties with rates exceeding 100%, signaling potential data inconsistencies or mismatches that warrant further review.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb172"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb172-1"><a href="#cb172-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(snap_map_data<span class="sc">$</span>snap_admin_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.1032  0.1628  0.1791  0.2299  2.9225 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb174"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb174-1"><a href="#cb174-1" aria-hidden="true" tabindex="-1"></a>snap_map_data <span class="sc">%&gt;%</span></span>
<span id="cb174-2"><a href="#cb174-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(snap_admin_rate <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb174-3"><a href="#cb174-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(fips, NAME, snap_admin_rate) <span class="sc">%&gt;%</span></span>
<span id="cb174-4"><a href="#cb174-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(snap_admin_rate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 2 features and 3 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -135.2191 ymin: 37.07211 xmax: -88.92789 ymax: 58.97497
Geodetic CRS:  NAD83
   fips    NAME snap_admin_rate                       geometry
1 02110  Juneau        2.922531 MULTIPOLYGON (((-134.7727 5...
2 17153 Pulaski        1.021957 MULTIPOLYGON (((-89.24857 3...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb176"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb176-1"><a href="#cb176-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb176-2"><a href="#cb176-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb176-3"><a href="#cb176-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb176-4"><a href="#cb176-4" aria-hidden="true" tabindex="-1"></a><span class="co"># === Step 1: Summarize SNAP households by county (admin data) ===</span></span>
<span id="cb176-5"><a href="#cb176-5" aria-hidden="true" tabindex="-1"></a>snap_admin_summary <span class="ot">&lt;-</span> snap_all <span class="sc">%&gt;%</span></span>
<span id="cb176-6"><a href="#cb176-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">GEOID =</span> <span class="fu">str_sub</span>(region_code, <span class="dv">1</span>, <span class="dv">5</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb176-7"><a href="#cb176-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(GEOID) <span class="sc">%&gt;%</span></span>
<span id="cb176-8"><a href="#cb176-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb176-9"><a href="#cb176-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">snap_households_admin =</span> <span class="fu">mean</span>(</span>
<span id="cb176-10"><a href="#cb176-10" aria-hidden="true" tabindex="-1"></a>      snap_all_households_public_assistance_participation <span class="sc">+</span></span>
<span id="cb176-11"><a href="#cb176-11" aria-hidden="true" tabindex="-1"></a>      snap_all_households_non_public_assistance_participation,</span>
<span id="cb176-12"><a href="#cb176-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb176-13"><a href="#cb176-13" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb176-14"><a href="#cb176-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb176-15"><a href="#cb176-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb176-16"><a href="#cb176-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb176-17"><a href="#cb176-17" aria-hidden="true" tabindex="-1"></a><span class="co"># === Step 2: Merge with ACS data and calculate participation rate ===</span></span>
<span id="cb176-18"><a href="#cb176-18" aria-hidden="true" tabindex="-1"></a>snap_rates_combined <span class="ot">&lt;-</span> snap_county <span class="sc">%&gt;%</span></span>
<span id="cb176-19"><a href="#cb176-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(GEOID, <span class="at">total_households_acs =</span> total_households) <span class="sc">%&gt;%</span></span>
<span id="cb176-20"><a href="#cb176-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(snap_admin_summary, <span class="at">by =</span> <span class="st">"GEOID"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb176-21"><a href="#cb176-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb176-22"><a href="#cb176-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">snap_admin_rate =</span> snap_households_admin <span class="sc">/</span> total_households_acs,</span>
<span id="cb176-23"><a href="#cb176-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">admin_data_available =</span> <span class="sc">!</span><span class="fu">is.na</span>(snap_households_admin)</span>
<span id="cb176-24"><a href="#cb176-24" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb176-25"><a href="#cb176-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb176-26"><a href="#cb176-26" aria-hidden="true" tabindex="-1"></a><span class="co"># === Step 3: Summarize how many counties are missing admin data ===</span></span>
<span id="cb176-27"><a href="#cb176-27" aria-hidden="true" tabindex="-1"></a>snap_rates_combined <span class="sc">%&gt;%</span></span>
<span id="cb176-28"><a href="#cb176-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb176-29"><a href="#cb176-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_counties =</span> <span class="fu">n</span>(),</span>
<span id="cb176-30"><a href="#cb176-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">with_admin_data =</span> <span class="fu">sum</span>(admin_data_available),</span>
<span id="cb176-31"><a href="#cb176-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing_admin_data =</span> <span class="fu">sum</span>(<span class="sc">!</span>admin_data_available)</span>
<span id="cb176-32"><a href="#cb176-32" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  total_counties with_admin_data missing_admin_data
           &lt;int&gt;           &lt;int&gt;              &lt;int&gt;
1           3142            2480                662</code></pre>
</div>
</div>
<p>To address missing SNAP participation rates in the administrative data, we imputed values using the ACS-derived participation rates for the same counties. This approach ensures complete coverage for analysis while preserving fidelity to observed ACS data where administrative gaps exist.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb178"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb178-1"><a href="#cb178-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First ensure snap_rate exists in snap_county (you may have already done this)</span></span>
<span id="cb178-2"><a href="#cb178-2" aria-hidden="true" tabindex="-1"></a>snap_county <span class="ot">&lt;-</span> snap_county <span class="sc">%&gt;%</span></span>
<span id="cb178-3"><a href="#cb178-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">snap_rate_acs =</span> snap_households <span class="sc">/</span> total_households)</span>
<span id="cb178-4"><a href="#cb178-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb178-5"><a href="#cb178-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge ACS rate into the combined dataset</span></span>
<span id="cb178-6"><a href="#cb178-6" aria-hidden="true" tabindex="-1"></a>snap_rates_combined <span class="ot">&lt;-</span> snap_rates_combined <span class="sc">%&gt;%</span></span>
<span id="cb178-7"><a href="#cb178-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(snap_county <span class="sc">%&gt;%</span> <span class="fu">select</span>(GEOID, snap_rate_acs), <span class="at">by =</span> <span class="st">"GEOID"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb178-8"><a href="#cb178-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb178-9"><a href="#cb178-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">snap_admin_rate_filled =</span> <span class="fu">if_else</span>(</span>
<span id="cb178-10"><a href="#cb178-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">is.na</span>(snap_admin_rate),</span>
<span id="cb178-11"><a href="#cb178-11" aria-hidden="true" tabindex="-1"></a>      snap_rate_acs,</span>
<span id="cb178-12"><a href="#cb178-12" aria-hidden="true" tabindex="-1"></a>      snap_admin_rate</span>
<span id="cb178-13"><a href="#cb178-13" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb178-14"><a href="#cb178-14" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We are checking for how many missing data values were filled with the ACS rate</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb179"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb179-1"><a href="#cb179-1" aria-hidden="true" tabindex="-1"></a>snap_rates_combined <span class="sc">%&gt;%</span></span>
<span id="cb179-2"><a href="#cb179-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb179-3"><a href="#cb179-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_counties =</span> <span class="fu">n</span>(),</span>
<span id="cb179-4"><a href="#cb179-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">originally_missing_admin =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(snap_admin_rate)),</span>
<span id="cb179-5"><a href="#cb179-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">filled_with_acs =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(snap_admin_rate) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(snap_admin_rate_filled)),</span>
<span id="cb179-6"><a href="#cb179-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">still_missing =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(snap_admin_rate_filled))</span>
<span id="cb179-7"><a href="#cb179-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  total_counties originally_missing_admin filled_with_acs still_missing
           &lt;int&gt;                    &lt;int&gt;           &lt;int&gt;         &lt;int&gt;
1           3142                      662             662             0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb181"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb181-1"><a href="#cb181-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tigris)</span>
<span id="cb181-2"><a href="#cb181-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb181-3"><a href="#cb181-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb181-4"><a href="#cb181-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb181-5"><a href="#cb181-5" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">tigris_use_cache =</span> <span class="cn">TRUE</span>)</span>
<span id="cb181-6"><a href="#cb181-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb181-7"><a href="#cb181-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Load and prepare U.S. counties shapefile</span></span>
<span id="cb181-8"><a href="#cb181-8" aria-hidden="true" tabindex="-1"></a>us_counties <span class="ot">&lt;-</span> <span class="fu">counties</span>(<span class="at">cb =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb181-9"><a href="#cb181-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>STATEFP <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"60"</span>, <span class="st">"66"</span>, <span class="st">"69"</span>, <span class="st">"72"</span>, <span class="st">"78"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb181-10"><a href="#cb181-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">GEOID =</span> <span class="fu">paste0</span>(STATEFP, COUNTYFP))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Retrieving data for the year 2022</code></pre>
</div>
<div class="sourceCode cell-code" id="cb183"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb183-1"><a href="#cb183-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Join with your combined SNAP rates dataset</span></span>
<span id="cb183-2"><a href="#cb183-2" aria-hidden="true" tabindex="-1"></a>map_data <span class="ot">&lt;-</span> us_counties <span class="sc">%&gt;%</span></span>
<span id="cb183-3"><a href="#cb183-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(snap_rates_combined, <span class="at">by =</span> <span class="st">"GEOID"</span>)</span>
<span id="cb183-4"><a href="#cb183-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb183-5"><a href="#cb183-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Plot the map using snap_admin_rate_filled</span></span>
<span id="cb183-6"><a href="#cb183-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Plot the map, excluding rates &gt; 1 (100%)</span></span>
<span id="cb183-7"><a href="#cb183-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb183-8"><a href="#cb183-8" aria-hidden="true" tabindex="-1"></a>  map_data <span class="sc">%&gt;%</span> </span>
<span id="cb183-9"><a href="#cb183-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(snap_admin_rate_filled <span class="sc">&lt;=</span> <span class="dv">1</span>)  <span class="co"># exclude invalid rates</span></span>
<span id="cb183-10"><a href="#cb183-10" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb183-11"><a href="#cb183-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> snap_admin_rate_filled), <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb183-12"><a href="#cb183-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(</span>
<span id="cb183-13"><a href="#cb183-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">option =</span> <span class="st">"plasma"</span>,</span>
<span id="cb183-14"><a href="#cb183-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.value =</span> <span class="st">"gray90"</span>,</span>
<span id="cb183-15"><a href="#cb183-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">"SNAP Participation Rate"</span>,</span>
<span id="cb183-16"><a href="#cb183-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>(<span class="at">accuracy =</span> <span class="dv">1</span>)</span>
<span id="cb183-17"><a href="#cb183-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb183-18"><a href="#cb183-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb183-19"><a href="#cb183-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"SNAP Participation Rates by County (Admin + ACS Imputed)"</span>,</span>
<span id="cb183-20"><a href="#cb183-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Filled with ACS rates where administrative data was missing"</span></span>
<span id="cb183-21"><a href="#cb183-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb183-22"><a href="#cb183-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">crs =</span> <span class="dv">2163</span>) <span class="sc">+</span></span>
<span id="cb183-23"><a href="#cb183-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb183-24"><a href="#cb183-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb183-25"><a href="#cb183-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">16</span>),</span>
<span id="cb183-26"><a href="#cb183-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"bottom"</span></span>
<span id="cb183-27"><a href="#cb183-27" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projectworkrevised_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>